#%RAML 1.0 NamedExample
value:
  Products:
    - Code: '5'
      Name: Product 1
      Description: Product 1 Description
      ProductType: 'Checking'
    - Code: '6'
      Name: Product 2
      Description: Product 2 Description
      ProductType: 'Savings'  
  RequestUUID: '9d08dc0d-86ea-4061-bc12-abd34e59d7ae'
