#%RAML 1.0 NamedExample
value:
  Promotion: 
    Status: 'New'
  OnboardingInvitation:
    FirstName: 'John'
    LastName: 'Smith'
    EmailAddress: 'email.address@gmail.com'
    PhoneNumber: '893-929-9391'
  RequestUUID: '9d08dc0d-86ea-4061-bc12-abd34e59d7ae'